version: '3.9'

services:
  web:
    depends_on:
      db:
        condition: service_healthy
    build: ./pointsApp
    env_file:
      - .web.env
    ports:
      - "8002:5000"
    networks:
      - web
      - database

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - database
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d examen"]
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  web:
    name: web

  database:
    name: database

volumes:
  db_data: